#!/bin/bash

sudo /opt/homebrew/bin/yabai --load-sa
sudo yabai --load-sa
/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# global settings
/opt/homebrew/bin/yabai -m config mouse_follows_focus          on
/opt/homebrew/bin/yabai -m config focus_follows_mouse          autoraise
/opt/homebrew/bin/yabai -m config window_origin_display        default
/opt/homebrew/bin/yabai -m config window_placement             second_child
/opt/homebrew/bin/yabai -m config window_topmost               off
/opt/homebrew/bin/yabai -m config window_shadow                on
/opt/homebrew/bin/yabai -m config window_opacity               off
/opt/homebrew/bin/yabai -m config window_opacity_duration      2000.0
/opt/homebrew/bin/yabai -m config active_window_opacity        1.0
/opt/homebrew/bin/yabai -m config normal_window_opacity        0.85
/opt/homebrew/bin/yabai -m config window_border                off
/opt/homebrew/bin/yabai -m config window_border_width          6
/opt/homebrew/bin/yabai -m config active_window_border_color   0xff775759
/opt/homebrew/bin/yabai -m config normal_window_border_color   0xff555555
/opt/homebrew/bin/yabai -m config insert_feedback_color        0xffd75f5f
/opt/homebrew/bin/yabai -m config split_ratio                  0.50
/opt/homebrew/bin/yabai -m config auto_balance                 off
/opt/homebrew/bin/yabai -m config mouse_modifier               alt 
/opt/homebrew/bin/yabai -m config mouse_action1                move
/opt/homebrew/bin/yabai -m config mouse_action2                resize
/opt/homebrew/bin/yabai -m config mouse_drop_action            swap

# general space settings
/opt/homebrew/bin/yabai -m config layout                       bsp
/opt/homebrew/bin/yabai -m config top_padding                  00
/opt/homebrew/bin/yabai -m config bottom_padding               00
/opt/homebrew/bin/yabai -m config left_padding                 00
/opt/homebrew/bin/yabai -m config right_padding                00
/opt/homebrew/bin/yabai -m config window_gap                   00
# 在yabai配置文件中启用信号功能
yabai -m config signal_active 1

# yabai -m config window_animation_duration    0.00

# focus
# yabai -m signal --add event=window_destroyed action=  "${HOME}"/.config/yabai/scripts/focus.sh
# yabai -m signal --add event=window_minimized action=  "${HOME}"/.config/yabai/scripts/focus.sh
# yabai -m signal --add event=application_hidden action="${HOME}"/.config/yabai/scripts/focus.sh
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
yabai -m signal --add event=window_destroyed \
  action="${functions[focus_under_cursor]}"
yabai -m signal --add event=window_minimized \
  action="${functions[focus_under_cursor]}"
yabai -m signal --add event=application_hidden \
  action="${functions[focus_under_cursor]}"

function focus_under_cursor {
  if yabai -m query --windows --space |
      jq -er 'map(select(.focused == 1)) | length == 0' >/dev/null; then
    yabai -m window --focus mouse 2>/dev/null || true
  fi
}




# system
# /opt/homebrew/bin/yabai -m rule --add app="^Finder*" layer=above manage=off border=off
/opt/homebrew/bin/yabai -m rule --add app="^System Settings*" manage=off 

/opt/homebrew/bin/yabai -m rule --add app="^Squirrel" manage=off 

/opt/homebrew/bin/yabai -m rule --add app="^iStat Menus*" sticky=on layer=above manage=off border=off

# IDEA
# /opt/homebrew/bin/yabai -m rule --add app="IntelliJ IDEA" subrole="AXDialog" manage=on
# /opt/homebrew/bin/yabai -m rule --add app="IntelliJ IDEA" subrole!="AXDialog" manage=off

# QQ
/opt/homebrew/bin/yabai -m rule --add app="QQ" title="QQ" manage=on
/opt/homebrew/bin/yabai -m rule --add app="QQ" title!="QQ" manage=off

# WeChat
/opt/homebrew/bin/yabai -m rule --add app="WeChat" title="WeChat" manage=on
/opt/homebrew/bin/yabai -m rule --add app="WeChat" title!="WeChat" manage=off
# yabai -m rule -add app="^WeChat$" title="^WeChat \(Window\)$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="WeChat" title="WeChat" manage=on
# /opt/homebrew/bin/yabai -m rule --add app="WeChat" title!="WeChat" manage=off

# ARC
# yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
# yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off
# apps=$(awk -v ORS='|' '{if($0!="") print $0}' $XDG_CONFIG_HOME/yabai/yabaimanaged)
# yabai -m rule --add app!="^${apps%?}$" manage=off
# yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

#book
yabai -m signal --add event=window_created app=Books action='"${HOME}"/.config/yabai/scripts/book.sh'
yabai -m rule --add app="Books" title="Home" manage=off
# yabai -m rule --add title='All' app='Books' action='"${HOME}"/.config/yabai/scripts/book.sh'

# echo "yabai configuration loaded.."

