#! /bin/bash
# # opens iTerm2
alt - return : "${HOME}"/.config/skhd/scripts/open_iterm2.sh

# space
alt - i : "${HOME}"/.config/skhd/scripts/screen-space.sh


# 窗口聚焦
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# 交换窗口
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# 移动窗口
shift + alt + ctrl - h : yabai -m window --warp west
shift + alt + ctrl - h : yabai -m window --warp south
shift + alt + ctrl - h : yabai -m window --warp north
shift + alt + ctrl - h : yabai -m window --warp east

# 旋转窗口布局
alt - r : yabai -m space --rotate 90

# 全屏
alt -f : yabai -m window --toggle zoom-fullscreen

# 设置/取消窗口 space
alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# 挂起窗口至屏幕中央/取消挂起窗口
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

# 修改窗口切分方式
alt - e : yabai -m window --toggle split

# 重置窗口布局
shift + alt - 0 : yabai -m space --balance


# Switch to specific space using Option + number
# 切换桌面
alt - 1 : /opt/homebrew/bin/yabai -m space --focus 1
alt - 2 : /opt/homebrew/bin/yabai -m space --focus 2
alt - 3 : /opt/homebrew/bin/yabai -m space --focus 3
alt - 4 : /opt/homebrew/bin/yabai -m space --focus 4
alt - 5 : /opt/homebrew/bin/yabai -m space --focus 5
alt - 6 : /opt/homebrew/bin/yabai -m space --focus 6
alt - 7 : /opt/homebrew/bin/yabai -m space --focus 7
alt - 8 : /opt/homebrew/bin/yabai -m space --focus 8
alt - 9 : /opt/homebrew/bin/yabai -m space --focus 9


# Move window to space and focus on it
# # 移动窗口至特定桌面
shift + alt - 1 : /opt/homebrew/bin/yabai -m window --space 1 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 1
shift + alt - 2 : /opt/homebrew/bin/yabai -m window --space 2 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 2
shift + alt - 3 : /opt/homebrew/bin/yabai -m window --space 3 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 3
shift + alt - 4 : /opt/homebrew/bin/yabai -m window --space 4 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 4
shift + alt - 5 : /opt/homebrew/bin/yabai -m window --space 5 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 5
shift + alt - 6 : /opt/homebrew/bin/yabai -m window --space 6 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 6
shift + alt - 7 : /opt/homebrew/bin/yabai -m window --space 7 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 7
shift + alt - 8 : /opt/homebrew/bin/yabai -m window --space 8 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 8
shift + alt - 9 : /opt/homebrew/bin/yabai -m window --space 9 && sleep 0.1 && /opt/homebrew/bin/yabai -m space --focus 9
# shift + alt - 1 : /opt/homebrew/bin/yabai -m window --space 1 && /opt/homebrew/bin/yabai -m space --focus 1
# shift + alt - 2 : /opt/homebrew/bin/yabai -m window --space 2 && /opt/homebrew/bin/yabai -m space --focus 2
# shift + alt - 3 : /opt/homebrew/bin/yabai -m window --space 3 && /opt/homebrew/bin/yabai -m space --focus 3
# shift + alt - 4 : /opt/homebrew/bin/yabai -m window --space 4 && /opt/homebrew/bin/yabai -m space --focus 4
# shift + alt - 5 : /opt/homebrew/bin/yabai -m window --space 5 && /opt/homebrew/bin/yabai -m space --focus 5
# shift + alt - 6 : /opt/homebrew/bin/yabai -m window --space 6 && /opt/homebrew/bin/yabai -m space --focus 6
# shift + alt - 7 : /opt/homebrew/bin/yabai -m window --space 7 && /opt/homebrew/bin/yabai -m space --focus 7
# shift + alt - 8 : /opt/homebrew/bin/yabai -m window --space 8 && /opt/homebrew/bin/yabai -m space --focus 8
# shift + alt - 9 : /opt/homebrew/bin/yabai -m window --space 9 && /opt/homebrew/bin/yabai -m space --focus 9
# shift + alt - 1 :/Users/brief/.config/skhd/script/space-switch.sh 1
# shift + alt - 2 :/Users/brief/.config/skhd/script/space-switch.sh 2
# shift + alt - 3 :/Users/brief/.config/skhd/script/space-switch.sh 3
# shift + alt - 4 :/Users/brief/.config/skhd/script/space-switch.sh 4
# shift + alt - 5 :/Users/brief/.config/skhd/script/space-switch.sh 5
# shift + alt - 6 :/Users/brief/.config/skhd/script/space-switch.sh 6
# shift + alt - 7 :/Users/brief/.config/skhd/script/space-switch.sh 7
# shift + alt - 8 :/Users/brief/.config/skhd/script/space-switch.sh 8
# shift + alt - 9 :/Users/brief/.config/skhd/script/space-switch.sh 9


# Resize windows
lctrl + alt - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
lctrl + alt - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
lctrl + alt - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
lctrl + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# start app
# alt - return : /Applications/iTerm.app
